.TH LV2BENCH 1 "08 Aug 2022"

.SH NAME
.B lv2bench \- benchmark LV2 plugins
.SH SYNOPSIS
.B lv2bench
[\fI\,OPTION\/\fR]... [\fI\,PLUGIN_URI\/\fR]

.SH OPTIONS
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit

.TP
\fB\-b BLOCK_SIZE\fR
Block size in audio frames

.TP
\fB\-h\fR, \fB\-\-help\fR
Display help and exit

.TP
\fB\-n FRAMES\fR
Total number of audio frames to process

.SH "SEE ALSO"
.BR lv2ls(1)

.SH AUTHOR
lv2bench was written by David Robillard <d@drobilla.net>
